### PR TITLE
Update language

### PR DESCRIPTION
**Pull request by rosiel**
as this page is no longer the README, and also we aren't calling this software "8".

**GitHub Issue**: none

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?

I noticed some legacy language and attempted to fix it. 

# What's new?

See diff.

# How should this be tested?

# Additional Notes:

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/8-x-committers

### CODE REVIEW

**Review by seth-shaw-unlv — APPROVED** [review]
👍

**Review by elizoller — APPROVED** [review]
seems straightforward to me

**Comment by elizoller** [comment]
oh lol seth already is on it haha

**Comment by seth-shaw-unlv** [comment]
Just by seconds, if that! 😂

**Pull request merged**
