### PR TITLE
d9 updates

### PR DESCRIPTION
**Pull request by elizoller**
**GitHub Issue**: (https://github.com/Islandora/migrate_islandora_csv/issues/39)

Slack conversation with @benglis

# What does this Pull Request do?

Updates for D9 
# What's new?
* composer updates
* info update
* migration changes

# How should this be tested?

* pull down PR
* install module (if not already installed)
* update composer (if not already update)
* `drush config:import --partial --source /var/www/html/drupal/web/modules/contrib/migrate_islandora_csv` (if not running on a newly enabled module
* now you should be able to do `drush migrate:import migration_name_here`

# Interested parties
@Islandora/8-x-committers @benglis

### CODE REVIEW

**Comment by dannylamb** [comment]
Looks like I've wound up testing this for ya :smile:

**Comment by elizoller** [comment]
is it working for you ok?

**Comment by dannylamb** [comment]
Works just fine.  I'm merging :+1:

**Review by dannylamb — APPROVED** [review]
I ran it like this and it worked just fine on d9
```
drush mim --userid=1 --uri=http://localhost:8000 --group migrate_islandora_csv
```

**Pull request merged**
